### ISSUE TITLE
Acrescentar página com "estrutura de produto" (BOM)

### ISSUE THREAD

**Issue by magsilva** [GuiNoya/solar-station#2]
Acrescentar página com "estrutura de produtos" (Bill of Material) necessários para a construção do projeto. Nesta lista (componente, quantidade, preço médio). Pode ser uma tabela ou uma estrutura hierárquica.

Ao final da página, indique também os locais em que é possível adquirir tais componentes ou, se preferir, indique isto na própria tabela.

**Comment by GuiNoya** [comment]
Feito.
