### ISSUE TITLE
Ajustar valor do sleep() no sensor de luminosidade

### ISSUE THREAD

**Issue by magsilva** [GuiNoya/solar-station#5]
O sensor de luminosidade é lido a cada 30 segundos. Entretanto, quão boa é a medida dele considerando este intervalo de tempo? Se no exato instante que foi lido o sensor ocorreu uma obstrução, mas foi algo instantâneo, será que a leitura foi "justa"?

Uma opção é ler o sensor com mais frequência e calcular a média por um período de tempo (por exemplo, ler a cada 500 ms e calcular a média a cada 30 segundos). Obstruções rápidas e que não afetariam a produção de energia poderiam ser descartadas e o dado seria mais representativo do período analisado.

**Comment by Gabrielle7** [comment]
O valor foi ajustado para o cenário. Estava com o valor padrão do MySensors, que é o tempo de espera mais comum para tal sensor. Optamos por não fazer a média, pois qualquer processamento de dados ficaria a cargo do usuário, não do sensor em si.
