### ISSUE TITLE
Interrupção no sensor de presença

### ISSUE THREAD

**Issue by magsilva** [GuiNoya/solar-station#6]
No sketch do sensor de presença, o sleep() do MyGateway() permite acordar quando ocorrer uma interrupção:

```
gw.sleep(INTERRUPT,CHANGE, SLEEP_TIME);
```

Entretanto, o valor de INTERRUPT não está definido. Mesmo adotando que o padrão seja o correspondente ao pino 2, no sketch este pino não é utilizado pelo sensor de presença (é o módulo para comunicação sem fio que está ligado nele).

**Comment by Gabrielle7** [comment]
Correção feita. Na verdade, o pino de entrada estava trocado com do sensor DHT. A leitura do de presença é feita no pino 3, que também é um pino de interrupção do Arduino Uno.
